import {prefix} from "../Utils"
import Config from "../../Config/Config"

// i found a thing online with a list of english to spanish translations so i copy pasted
// i could make it use google translate but too lazy!

let emotes = {    
  "hello": "hola",
  "the": "el",
  "of": "de",
  "and": "y",
  "a": "un",
  "to": "a",
  "in": "en",
  "is": "es",
  "you": "tu",
  "me": "yo",
  "that": "ese",
  "it": "eso",
  "he": "el",
  "was": "estaba",
  "for": "por",
  "on": "en",
  "are": "son",
  "as": "como",
  "with": "con",
  "his": "su",
  "they": "ellos",
  "i": "yo",
  "at": "a",
  "be": "ser",
  "this": "este",
  "have": "tener",
  "from": "de",
  "or": "o",
  "one": "uno",
  "had": "tenido",
  "by": "por",
  "word": "palabra",
  "but": "pero",
  "not": "no",
  "what": "que",
  "all": "todos",
  "were": "fueron",
  "we": "nosotros",
  "when": "cuando",
  "your": "su",
  "ur": "su",
  "can": "pueden",
  "said": "dijo",
  "there": "alla",
  "use": "usar",
  "an": "un",
  "each": "cada",
  "which": "cual",
  "she": "ella",
  "do": "hacer",
  "how": "cómo",
  "their": "sus",
  "if": "si",
  "will": "voluntad",
  "up": "arriba",
  "other": "otro",
  "about": "sobre",
  "out": "afuera",
  "many": "muchos",
  "then": "despues",
  "them": "a ellos",
  "these": "estas",
  "so": "asi que",
  "some": "alguno",
  "her": "la",
  "would": "haria",
  "make": "hacer",
  "like": "gusta",
  "him": "a el",
  "into": "dentro",
  "time": "tiempo",
  "has": "posee",
  "look": "mira",
  "more": "mas",
  "write": "escribe",
  "go": "vamos",
  "see": "ver",
  "number": "numero",
  "way": "camino",
  "could": "pudo",
  "people": "gente",
  "my": "mis",
  "than": "que",
  "first": "primero",
  "water": "agua",
  "been": "estado",
  "call": "llamar",
  "who": "quien",
  "oil": "aceite",
  "its": "su",
  "now": "ahora",
  "find": "encontrar",
  "long": "largo",
  "down": "abajo",
  "day": "dia",
  "did": "hizo",
  "get": "obtener",
  "come": "venir",
  "made": "hecha",
  "part": "parte",
  "one": "uno",
  "two": "dos",
  "three": "tres",
  "four": "cautro",
  "five": "cinco",
  "six": "seis",
  "seven": "siete",
  "eight": "ocho",
  "nine": "nueve",
  "ten": "diez",
  "eleven": "once",
  "twelve": "doce",
  "january": "enero",
  "february": "febrero",
  "march": "marzo",
  "april": "abril",
  "may": "mayo",
  "june": "junio",
  "july": "julio",
  "august": "agosto",
  "september": "septiembre",
  "october": "octubre",
  "november": "noviembre",
  "december": "diciembre",
  "coding": "codificación",
  "im": "yo soy",
  "am": "soy",
  "children": "niños",
  "fourteen": "catorce",
  "years": "años",
  "old": "antiguo",
  "guys": "tipo",
  "doing": "haciendo",
  "yall": "todos ustedes",
  "spanish": "español",
  "best": "el mejor",
  "language": "idioma",
  "learn": "aprender",
  "learnt": "aprendió",
  "learning": "aprendizaje",
  "left": "salió",
  "good": "bueno",
  "kinda": "tanto",
  "smell": "oler",
  "joined": "entrada",
  "men": "hombres",
  "women": "mujeres",
  "brother": "hermano",
  "sister": "hermana",
  "brothers": "hermanos",
  "sisters": "hermanas",
  "anyone": "cualquiera",
  "play": "juego",
  "wanna": "querer",
  "playing": "jugando",
  "love": "encanta",
  "hate": "odio",
  "penis": "pene",
  "cock": "polla",
  "dick": "polla",
  "bad": "malo",
  "here": "aquí",
  "friend": "amigo",
  "speak": "hablo",
  "where": "donde",
  "live": "vivo",
  "really": "verdad",
  "too": "tambien",
  "much": "demasiado",
  "alot": "mucho",
  "heyo": "Buenos días",
  "hi": "hola",
  "goodevening": "Buenas tardes",
  "wyd": "Qué tal",
  "wyd?": "¿Qué haces?",
  "hey": "ey",
  "ello": "aló",
  "oi": "aló",
  "yoohoo": "¡aló!", // goofy ahh word who tf says yoohoo
  "bye": "hasta luego",
  "cya": "adios",
  "thanks": "gracias",
  "name": "llama",
  "weird": "extraño",
  "hacked": "hackeado",
  "cheats": "trampas",
  "cheater": "tramposo",
  "imagine": "imaginar",
  "cheating": "infiel",
  "weirdest": "más raro",
  "epic": "épico",
  "moment": "momento",
  "admins": "administradores",
  "goofy": "mentecato",
  "silly": "tonta",
  "bitch": "cabrona",
  "dumbass": "cabrón",
  "dumbasses": "cabróns",
  "shit": "mierda",
  "fuck": "joder",
  "fucking": "jodido",
  "kys": "suicidarte",
  "fat": "gordo",
  "fatass": "culo gordo",
  "fatasses": "culos gordos",
  "chunky": "fornido",
  "scam": "engañar",
  "scammer": "estafador",
  "games": "jugadores",
  "sweat": "sudor",
  "swear": "jurar",
  "ass": "culo",
  "shitter": "cabrón",
  "what?": "¿qué?",
  "wha": "que-?",
  "nice": "bonito",
  "connection": "conexión",
  "why": "por qué",
  "why?": "¿por qué?",
  "queue": "cola",
  "open": "abierto",
  "wait": "espere",
  "queue": "cola",
  "game": "juego",
  "goal": "meta",
  "yes": "si",
  "help": "ayuda",
  "cant": "no poder",
  "stop": "deténgase",
  "yay": "hurra",
  "sent": "enviada",
  "You've": "tienes",
  "youve": "tienes",
  "due": "adeudado",
  "connection": "conexión",
  "connectivity.": "conexión",
  "being": "siendo",
  "please": "por favor",
  "neither": "ninguno de los dos",
  "fix": "fijae",
  "screenshare": "compartir pantalla",
  "position": "posición",
  "queued": "hacían cola",
  "english": "inglés",
  "because": "parque",
  "keyboard": "teclado",
  "sad": "triste",
  "sadge": "triste",
  "cry": "llorar",
  "crying": "llorando",
  "today": "este día",
  "shouting": "gritando",
  "kids": "niños",
  "funny": "gracioso",
  "fixed": "fijado",
  "mate": "compañero",
  "dont": "no",
  "probably": "probablemente",
  "probs": "probablemente",
  "through": "mediante",
  "mod": "modificación",
  "went": "se fue",
  "disconnected": "desconectado",
  "offline": "desconectado",
  "off": "apagado",
  "stuck": "atascado",
  "remove": "quitar",
  "ye": "si",
  "think": "pienso",
  "thats": "ese es",
  "soulbound": "alma atada",
  "soulbounded": "Atada al alma",
  "tell": "decir",
  "free": "libre",
  "u": "tu",
  "rat": "rato",
  "cool": "",
  "faggot": "maricón",
  "cool": "increíble",
  "incredible": "increíble",
  "awesome": "Asombroso",
  "friends": "amigos",
  "talking": "hablando",
  "guy": "chico",
  "ratted": "ratoed",
  "lie": "mentir",
  "gonna": "voya",
  "heart": "corazón",
  "whats": "qué",
  "join": "unirse",
  "enough": "suficiente",
  "need": "necesitar",
  "life": "vida",
  "intercourse": "coito",
  "sex": "sexo",
  "lied": "mintió",
  "gracias": "thanks",
  "sorry": "perdón",
  "got": "obtuvo",
  "eating": "comiendo",
  "eat": "comer",
  "balls": "pelotas",
  "ball": "pelota",
  "ask": "pedir",
  "asked": "pregunté",
  "pain": "dolor",
  "won": "ganó",
  "lost": "Perdió",
  "win": "victoria",
  "might": "puede que",
  "hole": "agujero",
  "fell": "cayó",
  "going": "yendo",
  "again": "otra vez",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  // emotes (had to be in same file as spanish to not cause problems) (this also means u need to have spanish to do the emotes ._.)
    "<33": "❤",
    ":star": "✮",
    ":yes": "✔",
    ":cross": "✖",
    ":java": "☕",
    ":arrow": "➜",
    ":shrug": "¯\_(ツ)_/¯",
    ":tableflip": "(╯°□°）╯︵ ┻━┻",
    "o//": "( ﾟ◡ﾟ)/",
    ":totem": "☉_☉",
    ":typing": "✎...",
    ":maths": "√(π+x)=L",
    ":snail": "@'-'",
    ":thinking": "(0.o?)",
    ":gimme": "༼つ◕_◕༽つ",
    ":wizard": "('-')⊃━☆ﾟ.*･｡ﾟ",
    ":pvp": "⚔",
    ":peace": "✌",
    ":puffer": "<('O')>",
    ":yey": "ヽ (◕◡◕) ﾉ",
    ":cat": "= ＾● ⋏ ●＾ =",
    ":dab": "<o/",
    ":dj": "ヽ(⌐■_■)ノ♬",
    ":snow": "☃",
    "h//": "ヽ(^◇^*)/",
    ":sloth": "(・⊝・)",
    ":cute": "(✿◠‿◠)",
    ":dog": "(ᵔᴥᵔ)",
    "ez": "ｅｚ"
  }
  register("messageSent", (message, event) => {
    let replaced = false
    message = message.split(" ")
    for (let i = 0; i < message.length; i++) {
      if (!Config.spanish) return;
        if (Object.keys(emotes).includes(message[i])) {
            replaced = true
            message[i] = emotes[message[i]]
        }
    }
    message = message.join(" ")
    if (!replaced) return
    cancel(event)
    ChatLib.say(message)
  })

  register("command", () => {
    ChatLib.chat(`
${prefix} &b&lemotes&f:
    &6<33 &f- &c❤
    &6:star &f- &6✮
    &6:yes &f- &a✔
    &6:cross &f- &c✖
    &6:java &f- &b☕
    &6:arrow &f- &e➜
    &6:shrug &f- &e¯\_(ツ)_/¯
    &6:tableflip &f- &c(╯°□°）╯&f︵ &7┻━┻
    &6o// &f- &d( ﾟ◡ﾟ)/
    &6:totem &f- &b☉&e_&b☉
    &6:typing &f- &e✎&6...
    &6:maths &f- &a&l√&e&l(&a&lπ+x&e&l)&a&l=&c&lL
    &6:snail &f- &e@&a'&e-&a'
    &6:thinking &f- &6(&a0&6.&ao&c?&6)
    &6:gimme &f- &b༼つ◕_◕༽つ
    &6:wizard &f- &e(&b'&e-&b'&e)⊃&c━&d☆ﾟ.*･｡ﾟ
    &6:pvp &f- &e⚔
    &6:peace &f- &a✌
    &6:puffer &f- &e<('O')>
    &6:yey &f- &aヽ (◕◡◕) ﾉ
    &6:cat &f- &e= &b＾● ⋏ ●＾ &e=
    &6:dab &f- &d<&eo&d/
    &6:dj &f- &1ヽ&5(&d⌐&c■&6_&e■&b)&3ノ&9♬
    &6:snow &f- &b☃
    &6h// &f- &eヽ(^◇^*)/
    &6:sloth &f- &6(&7・&6⊝&7・&6)
    &6:cute &f- &e(&a✿&e◠‿◠)
    &6:dog &f- &6(ᵔᴥᵔ)
    &6ez &f- &aｅｚ`)}).setName("memotes")